# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d87d79828c003b17050c8b4d47a9cdaadb71a613060854843ed192953605c543eb87f907c112c204bea97ec124655cef894fadb736c72ab8f4e874164a11d066

test:
  secret_key_base: db7177ca4a0d86c7b2e9fa963fe148fa2abc287e0c92dc271f517c281937c9bee59d8cb82272cf16b411eb5f476cee0c3f65a071bce3de98262971baf71674f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
